spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASS}@${MONGO_HOST}:27017/${MONGO_DATABASE}
  application:
    name: spec-finder
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG

excel-parser:
  index-of-header: ${INDEX_OF_HEADER}
  index-of-param: ${INDEX_OF_PARAM}
  count-left-offset: ${COUNT_LEFT_OFFSET}
